service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  dadJoke:
    handler: src/handler.dadJoke
    events:
      - http:
          method: get
          path: dad-joke
