service:
  name: dad-joke-twitter-bot

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  profile: personal

functions:
  dadJoke:
    handler: src/handler.dadJoke
    events:
      - schedule: cron(0 9 * * ? *)
